[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT wsgi:application" 